### ISSUE TITLE
Some issues with EtTu

### ISSUE THREAD

**Issue by burner1024** [FakelsHub/InventoryFilter#2]
Just tried with EtTu, noticed some issues:
1. Upon filter installation, `AllowUnsafeScripting` is changed to 0 for some reason.
2. Missing "drop all" (I think) image:
![Captura de pantalla de 2020-02-17 14-48-56](https://user-images.githubusercontent.com/1279852/74633637-a5639d00-5194-11ea-8a4f-cbd6b7a1fb3f.png)

**Comment by FakelsHub** [comment]
У меня нет никакеих проблем с графикой кнопки и с переопределением значения в опции.
проверь файл dropall_up.pcx для кнопки.

**Comment by burner1024** [comment]
Перепроверил. Кнопка работает, это что-то у меня было не то. А вот опцию сбрасывает.

![Captura de pantalla de 2020-03-01 01-50-48](https://user-images.githubusercontent.com/1279852/75613371-70295880-5b5f-11ea-9301-8fbba9a30c3f.png)

![Captura de pantalla de 2020-03-01 01-51-01](https://user-images.githubusercontent.com/1279852/75613373-728bb280-5b5f-11ea-9242-99cbec66017e.png)

Он у тебя переключает ее туда-сюда или именно ставит? Потому что F1in2 ее заранее включает сам.

**Comment by FakelsHub** [comment]
Ставит. для установки используется bat-ник windows, так что на unix это может и не работать.

**Comment by FakelsHub** [comment]
> это что-то у меня было не то. 

Это было не только у тебя. причина неизвестна.

**Comment by burner1024** [comment]
Да, вероятно связано с wine. Батник конечно жутковатый, если что для UP я взял [initool](https://github.com/dbohdan/initool/): он как-то [попроще](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/c371fc35269cfbee7f508ea753e2d0dc56932b9b/release/upu-install.bat#L18).
