### ISSUE TITLE
"Unload all" button?

### ISSUE THREAD

**Issue by burner1024** [FakelsHub/InventoryFilter#3]
A button to unload all guns in inventory would come in handy at times, I think. After group figths especially.

**Comment by FakelsHub** [comment]
Непонял что хотим, какую кнопку?

**Comment by burner1024** [comment]
Все пушки в рюкзаке разрядить.

**Comment by FakelsHub** [comment]
А если некоторые ненужно разряжать. Потом их опять заряжать?.

**Comment by burner1024** [comment]
Ну... да. Насильно же пользоваться кнопкой никто не заставляет.

**Comment by FakelsHub** [comment]
ну получится не очень юзабельная кнопка. 
или разряжать те которые у NPC в инвентаре?

**Comment by burner1024** [comment]
Я имею ввиду то, что у главного героя в инвентаре (не в руках).
Про NPC даже не понял. Партийцы имеются ввиду? Не знаю, такой надобности вроде не было.

**Comment by burner1024** [comment]
Смотри сам, мое дело предложить.

**Comment by FakelsHub** [comment]
Кстати а что за практика такая дурацкая разряжать каждое оружие?
такого "садомазо" никогда не видел. да и сам таким не страдал.

**Comment by FakelsHub** [comment]
> Ну там, раздолбал работорговцев, собрал 20 пушек и сидишь как дурак кликаешь по каждой.
Про NPC даже не понял.

имел виду перед тем как забрать, нажимаешь и разряжается все оружие что лежит у трупа.

**Comment by burner1024** [comment]
Ну оружие продаешь, патроны оставляешь.
Если каждый раз ее на трупе нажимать, то особо смысла нет, то на то и выходит.

**Comment by FakelsHub** [comment]
в таком случае вам надо скрипт отдельный делать, по типу как уничтожение брони только на разряд у трупов.
Это будет эффективнее чем мало юзабельная кнопка.

**Comment by burner1024** [comment]
Ладно.
